name: rebloc
description: |
  A state management library for Flutter that combines aspects of
  Redux and BLoC. Rebloc uses streams and BLoCs to compose
  middleware and reducers.

version: 0.2.2
author: Andrew Brogdon <brogdon+github@gmail.com>
homepage: https://github.com/redbrogdon/rebloc

dependencies:
  rxdart: ^0.22.0
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.4.0 <3.0.0'
